(function($,undefined){var indexTopNav={init:function(){$(".index_top_nav .item_siteMap").hover(this.onSiteMapHover)
$(".index_top_nav .has_dropdown").hover(this.onNavItemHoverIn,this.onNavItemHOverOut);$(".index_top_nav .item_weixin, .index_top_nav .item_weibo").hover(function(){$(this).find(".header_icon").toggleClass("hover");});$(".index_top_nav .item_qrCode").hover(function(){$(this).find(".header_icon").toggleClass("active");});},onSiteMapHover:function(e){var offsetLeft=$(this).offset().left-$(".header_top .header_inner").offset().left+1;$(this).find(".siteMap_panel").css("left",0-offsetLeft+"px");},onNavItemHoverIn:function(e){$(this).addClass("item_hover");if(utility.isIELte(8)){$(this).find(".icon_arrow").addClass("icon_arrow_rotate");}},onNavItemHOverOut:function(e){$(this).removeClass("item_hover");if(utility.isIELte(8)){$(this).find(".icon_arrow").removeClass("icon_arrow_rotate");}}};var searchBox={init:function(){$("#keyword-input").focus(this.onInputFocus);$("#keyword-input").blur(this.onInputBlur);},onInputFocus:function(){$(this).parents(".tn_search_box").find(".search_hot").hide();},onInputBlur:function(){if($(this).val()==""){$(this).parents(".tn_search_box").find(".search_hot").show();}}};var localCity={}
var utility={isIELte:function(version){if(!$.browser.msie){return false;}
return parseInt($.browser.version)<=version;}};var searchAdvance={init:function(){$(function(){searchAdvance.getAll();});},getAll:function(){var _self=this;var url='http://s.tuniu.com/yii.php?r=search/search/callwidget&type=all';$.ajax({url:url,type:"get",async:true,dataType:"jsonp",jsonp:"js_callback",success:function(json){searchAdvance.advanceCallback(json);search_input.init();if(json.hot&&json.hot.length>0){_self.newHotSearch=true;_self.cjHotCallback(json);search_input.showPopBox($(".tn_s_input"),$("#searchInputBox"));}}});},getHot:function(){var _self=this;var url='http://s.tuniu.com/yii.php?r=search/search/callwidget&type=hot';$.ajax({url:url,type:"get",async:true,dataType:"jsonp",jsonp:"js_callback",success:function(json)
{searchAdvance.hotCallback(json);search_input.showPopBox($(".tn_s_input"),$("#searchInputBox"));}});},advanceCallback:function(json){if(json){$("body").append(json.advance);}},hotCallback:function(hotObj){if(hotObj){$("body").append(hotObj.hot);mouseClick();}},cookieClear:function(element){var url='http://s.tuniu.com/yii.php?r=search/search/ajaxAddCookie';$.ajax({url:url,type:"get",async:true,dataType:"jsonp",jsonp:"jsoncallback",success:function(json)
{$(element).parents('.sib_last_search').remove();}});},advanceSearch:function(){var params={};$(obj).parents('div[box="searchBox"]').find("dl[filter-type]").each(function(){var filterType=$(this).attr('filter-type');switch(filterType){case'keyword':var advanceFunc=function(inputStr){if(inputStr==false||inputStr==='请输入目的地、主题或关键词'){return false;}else{return true;}};var defKeyword=false;var inputStr=advanceFunc($(this).find("input").val());if(!(defKeyword&&inputStr))params['keywords']=false;if(inputStr){params['keywords']=$(this).find("input").val();}else if(defKeyword){params['keywords']=$("#keyword-input").val();};break;case'planDate':var startDate=$(this).find('input[name="start"]').val(),endDate=$(this).find('input[name="end"]').val();if(startDate!='yyyy-mm-dd')params['startDate']=startDate;if(endDate!='yyyy-mm-dd')params['endDate']=endDate;break;case'price':var min=$(this).find('input[name="min"]').val(),max=$(this).find('input[name="max"]').val();if(min!='')params['minPrice']=min;if(max!='')params['maxPrice']=max;break;case'prdType':var prdType=$(this).find('.checked').attr('filter-value');if(prdType!='0')params['prdType']=prdType;break;default:var option=new Array(),rel=true;$(this).find("a[filter-value]").each(function(){if($(this).attr("class")=='checked'){var filterValue=$(this).attr('filter-value');if(filterValue==0){rel=false;}else{option.push(filterValue);}}});if(rel)params[filterType]=option;}});if(!params.keywords){alert('请输入目的地、主题或关键词');return;}
$.ajax({type:'get',url:"http://s.tuniu.com/yii.php?r=search/search/getUrlForHomePage",data:{'data':params},dataType:"jsonp",jsonp:"js_callback",success:function(data){window.location.href=data;}});}};var indexNavMenu=function(){function showSubNav(item){if(!$(item).hasClass("hasSubNav")){return;}
$(item).addClass('cui_nav_o');var ThisL=$(item).offset().left,ThisW=$(item).width(),thisW=ThisW/2,winW=$('body').width(),menuW=$('ul.menu_list').width(),menuL=$('ul.menu_list').offset().left,liLeft=ThisL-menuL,subNavW=$(item).find('.top_sub_nav').width(),subNavWban=subNavW/2,navL=liLeft-subNavWban+thisW;$("#subnav_wrap_bg").show();$(item).find('.top_subnav_wrap').css({'width':menuW,'left':0});if(navL<0){navL=0;$(item).find('.top_sub_nav').css('left',0);}else{if(navL+subNavW>menuW){$(item).find('.top_sub_nav').css('right',0);}else{$(item).find('.top_sub_nav').css('left',navL);}}
$(item).find('.icon_arrowUp').css('left',liLeft+thisW-5);}
function closeSubNav(item){if(!$(item).hasClass("hasSubNav")){return;}
$("#subnav_wrap_bg").hide();$(item).removeClass('cui_nav_o');$(item).find('.top_sub_nav')[0].style.left=null;$(item).find('.top_sub_nav')[0].style.right=null;}
$(".index_nav_menu .menu_list>li").hover(function(){var self=this;var closeTimer=$(this).data("closeTimer");if(closeTimer){clearTimeout(closeTimer);$(this).data("closeTimer",null);}
var showTimer=$(this).data("showTimer");showTimer=setTimeout(function(){showSubNav($(self));$(self).data("showTimer",null);},100);$(this).data("showTimer",showTimer);},function(){var self=this;var showTimer=$(this).data("showTimer");if(showTimer){clearTimeout(showTimer);$(this).data("showTimer",null);}
var closeTimer=$(this).data("closeTimer");closeTimer=setTimeout(function(){closeSubNav($(self));$(self).data("closeTimer",null);},100);$(this).data("closeTimer",closeTimer);});}
window.indexNavMenu=indexNavMenu;var headerNavDest=function(){$(".header_nav .nav_dest").hover(function(){$(this).find(".allsort").show();$(this).find(".allsort .mc").show();},function(){$(this).find(".allsort").hide();$(this).find(".allsort .mc").show();});}
var refreshLoginState=function(){var user_login_info=document.getElementById("user_login_info");if(user_login_info){user_login_info.innerHTML=getLoginInfo();var collebox=document.getElementById("vipnameBox");var vipname=document.getElementById("vipname");if(collebox){collebox.onmouseover=function(){collebox.className="vipname_box on";vipname.className="vipname float_tt";},collebox.onmouseout=function(){collebox.className="vipname_box";vipname.className="vipname float_tt";vipname.className="vipname";}}}}
$(document).ready(function(){indexTopNav.init();searchBox.init();indexNavMenu();headerNavDest();refreshLoginState();changeAllPagePhone();});})(jQuery);function selectTag(showContent,selfObj){var tag=document.getElementById("tags").getElementsByTagName("li");var taglength=tag.length;for(i=0;i<taglength;i++){tag[i].className="";}
selfObj.parentNode.className="selectTag";for(i=1;j=document.getElementById("tagContent"+i);i++){j.style.display="none";}
document.getElementById(showContent).style.display="block";}
var startCity=document.getElementById("startCity");if(startCity){startCity.onmouseover=function(){startCity.className="head_start_city change_tab";};startCity.onmouseout=function(){startCity.className="head_start_city";};}
function getPhoneCookie(objName){var arrStr=document.cookie.split("; ");for(var i=0;i<arrStr.length;i++){var temp=arrStr[i].split("=");if(temp[0]==objName)return unescape(temp[1]);}
return false;}
function changeAllPagePhone(){var headPhoneBox=$(".header_search .site_contact");var footPhoneBox=$(".three_trav .thr_trav");var tuniuHeaderPhoneText=headPhoneBox.find(".text");var tuniuHeaderPhoneTel=headPhoneBox.find(".tel")
var tuniuFootPhoneText=footPhoneBox.find(".tn_text");var tuniuFootPhoneTel=footPhoneBox.find(".tn_phone");var tuniuPPhoneNumber=getPhoneCookie("p_phone_400");if(tuniuFootPhoneText.length>0){}
else{footPhoneBox.find("a").prepend("<em class='tn_text'></em>");var tuniuFootPhoneText=footPhoneBox.find(".tn_text");}
if(tuniuHeaderPhoneTel){if(tuniuPPhoneNumber&&tuniuPPhoneNumber=="4007-979797"){tuniuHeaderPhoneText.text("途致贵宾专线");tuniuHeaderPhoneTel.text(tuniuPPhoneNumber);}else{tuniuHeaderPhoneText.text("客户服务电话");tuniuHeaderPhoneTel.text("4007-999-999");}}
if(tuniuFootPhoneTel){if(tuniuPPhoneNumber&&tuniuPPhoneNumber=="4007-979797"){tuniuFootPhoneText.text("途致贵宾专线（免长途费）");tuniuFootPhoneTel.text(tuniuPPhoneNumber);}else{tuniuFootPhoneText.text("客户服务电话（免长途费）");tuniuFootPhoneTel.text("4007-999-999");}}}
$(function($){var sub=$("#keyword-input-sub").val();if(sub&&sub!=''){$("#keyword-input").val(sub);}});